version: '3.8'

services:
  elebackend:
    build: 
      context: electricity_biller
      dockerfile: Dockerfile
    ports:
      - '6000:6000'
  elefrontend:
    build: 
      context: elecat-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    