version: '3.8'

services:
  elebackend:
    build: 
      context: electricity_biller
      dockerfile: Dockerfile
    ports:
      - '6000:6000'
  elefrontend:
    build: 
      context: elecat-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/  